name: anotherci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  anotherreleaserelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
